# Generated by Django 4.1.2 on 2022-11-03 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApostaClientesMega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.CharField(max_length=200)),
                ('lista_numeros_apostados', models.IntegerField(default=1)),
                ('data_aposta', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MegaSena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista_numeros', models.IntegerField(default=1)),
                ('data_sorteio', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
